import { Document, Page, Text, View, StyleSheet, PDFDownloadLink } from "@react-pdf/renderer";
import { Download } from "lucide-react";

export default function ReportRenderer({ data }: { data: any }) {
  return (
    <PDFDownloadLink
      document={<ExecutiveReportPDF data={data} />}
      fileName={`Chaff_Security_Report_${new Date().toISOString().slice(0, 10)}.pdf`}
      className="inline-flex items-center justify-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 transition shadow-sm self-start mt-2"
    >
      {({ loading }) =>
        loading ? (
          "Generating document..."
        ) : (
          <>
            <Download className="h-4 w-4" /> Download PDF Report
          </>
        )
      }
    </PDFDownloadLink>
  );
}

const ExecutiveReportPDF = ({ data }: { data: any }) => (
  <Document>
    <Page size="A4" style={{ padding: 40, backgroundColor: "#ffffff" }}>
      <View style={{ marginBottom: 30, borderBottom: "1px solid #e5e7eb", paddingBottom: 15 }}>
        <Text style={{ fontSize: 24, color: "#111827", marginBottom: 5 }}>
          {data.title || "Executive Security Report"}
        </Text>
        <Text
          style={{ fontSize: 10, color: "#6b7280", textTransform: "uppercase", letterSpacing: 1 }}
        >
          {new Date().toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
          })}{" "}
          • CHAFF SECURITY
        </Text>
      </View>

      <View style={{ marginBottom: 25 }}>
        <Text
          style={{
            fontSize: 14,
            color: "#374151",
            marginBottom: 10,
            borderBottom: "1px solid #f3f4f6",
            paddingBottom: 5,
          }}
        >
          Executive Summary
        </Text>
        <Text style={{ fontSize: 11, color: "#4b5563", lineHeight: 1.6 }}>
          {data.executive_summary}
        </Text>
      </View>

      <View style={{ marginBottom: 25 }}>
        <Text
          style={{
            fontSize: 14,
            color: "#374151",
            marginBottom: 10,
            borderBottom: "1px solid #f3f4f6",
            paddingBottom: 5,
          }}
        >
          Traffic Insights
        </Text>
        <Text style={{ fontSize: 11, color: "#4b5563", lineHeight: 1.6 }}>
          {data.traffic_insights}
        </Text>
      </View>

      {data.top_threats && data.top_threats.length > 0 && (
        <View style={{ marginBottom: 25 }}>
          <Text
            style={{
              fontSize: 14,
              color: "#374151",
              marginBottom: 10,
              borderBottom: "1px solid #f3f4f6",
              paddingBottom: 5,
            }}
          >
            Top Threats
          </Text>
          {data.top_threats.map((t: any, i: number) => (
            <View
              key={i}
              style={{
                backgroundColor: "#f9fafb",
                borderLeft: "3px solid #ef4444",
                padding: 12,
                marginBottom: 10,
              }}
            >
              <Text style={{ fontSize: 12, color: "#111827", marginBottom: 4 }}>{t.name}</Text>
              <Text
                style={{
                  fontSize: 9,
                  color: "#ef4444",
                  textTransform: "uppercase",
                  marginBottom: 6,
                }}
              >
                SEVERITY: {t.severity}
              </Text>
              <Text style={{ fontSize: 10, color: "#4b5563", lineHeight: 1.5 }}>
                {t.description}
              </Text>
            </View>
          ))}
        </View>
      )}

      <View style={{ marginBottom: 25 }}>
        <Text
          style={{
            fontSize: 14,
            color: "#374151",
            marginBottom: 10,
            borderBottom: "1px solid #f3f4f6",
            paddingBottom: 5,
          }}
        >
          Conclusion
        </Text>
        <Text style={{ fontSize: 11, color: "#4b5563", lineHeight: 1.6 }}>{data.conclusion}</Text>
      </View>

      <Text
        style={{
          position: "absolute",
          bottom: 30,
          left: 40,
          right: 40,
          textAlign: "center",
          color: "#9ca3af",
          fontSize: 9,
          borderTop: "1px solid #f3f4f6",
          paddingTop: 10,
        }}
      >
        Confidential • Generated by Chaff Security Analyst AI
      </Text>
    </Page>
  </Document>
);
