/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrapSlugRouteImport } from './routes/trap.$slug'
import { Route as AppThreatsRouteImport } from './routes/app.threats'
import { Route as AppOnboardRouteImport } from './routes/app.onboard'
import { Route as AppMcpRouteImport } from './routes/app.mcp'
import { Route as AppHoneypotsRouteImport } from './routes/app.honeypots'
import { Route as AppHarvestRouteImport } from './routes/app.harvest'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAgentRouteImport } from './routes/app.agent'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AppCampaignsIndexRouteImport } from './routes/app.campaigns.index'
import { Route as AppCampaignsIdRouteImport } from './routes/app.campaigns.$id'
import { Route as ApiPublicBeaconRouteImport } from './routes/api/public/beacon'
import { Route as ApiPublicHooksRescanRouteImport } from './routes/api/public/hooks/rescan'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrapSlugRoute = TrapSlugRouteImport.update({
  id: '/trap/$slug',
  path: '/trap/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppThreatsRoute = AppThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardRoute = AppOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMcpRoute = AppMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AppRoute,
} as any)
const AppHoneypotsRoute = AppHoneypotsRouteImport.update({
  id: '/honeypots',
  path: '/honeypots',
  getParentRoute: () => AppRoute,
} as any)
const AppHarvestRoute = AppHarvestRouteImport.update({
  id: '/harvest',
  path: '/harvest',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicBeaconRoute = ApiPublicBeaconRouteImport.update({
  id: '/api/public/beacon',
  path: '/api/public/beacon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRescanRoute = ApiPublicHooksRescanRouteImport.update({
  id: '/api/public/hooks/rescan',
  path: '/api/public/hooks/rescan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/api/mcp': typeof ApiMcpRoute
  '/app/agent': typeof AppAgentRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/harvest': typeof AppHarvestRoute
  '/app/honeypots': typeof AppHoneypotsRoute
  '/app/mcp': typeof AppMcpRoute
  '/app/onboard': typeof AppOnboardRoute
  '/app/threats': typeof AppThreatsRoute
  '/trap/$slug': typeof TrapSlugRoute
  '/api/public/beacon': typeof ApiPublicBeaconRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/campaigns/': typeof AppCampaignsIndexRoute
  '/api/public/hooks/rescan': typeof ApiPublicHooksRescanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/api/mcp': typeof ApiMcpRoute
  '/app/agent': typeof AppAgentRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/harvest': typeof AppHarvestRoute
  '/app/honeypots': typeof AppHoneypotsRoute
  '/app/mcp': typeof AppMcpRoute
  '/app/onboard': typeof AppOnboardRoute
  '/app/threats': typeof AppThreatsRoute
  '/trap/$slug': typeof TrapSlugRoute
  '/api/public/beacon': typeof ApiPublicBeaconRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/campaigns': typeof AppCampaignsIndexRoute
  '/api/public/hooks/rescan': typeof ApiPublicHooksRescanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/api/mcp': typeof ApiMcpRoute
  '/app/agent': typeof AppAgentRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/harvest': typeof AppHarvestRoute
  '/app/honeypots': typeof AppHoneypotsRoute
  '/app/mcp': typeof AppMcpRoute
  '/app/onboard': typeof AppOnboardRoute
  '/app/threats': typeof AppThreatsRoute
  '/trap/$slug': typeof TrapSlugRoute
  '/api/public/beacon': typeof ApiPublicBeaconRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/campaigns/': typeof AppCampaignsIndexRoute
  '/api/public/hooks/rescan': typeof ApiPublicHooksRescanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/api/mcp'
    | '/app/agent'
    | '/app/dashboard'
    | '/app/harvest'
    | '/app/honeypots'
    | '/app/mcp'
    | '/app/onboard'
    | '/app/threats'
    | '/trap/$slug'
    | '/api/public/beacon'
    | '/app/campaigns/$id'
    | '/app/campaigns/'
    | '/api/public/hooks/rescan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/api/mcp'
    | '/app/agent'
    | '/app/dashboard'
    | '/app/harvest'
    | '/app/honeypots'
    | '/app/mcp'
    | '/app/onboard'
    | '/app/threats'
    | '/trap/$slug'
    | '/api/public/beacon'
    | '/app/campaigns/$id'
    | '/app/campaigns'
    | '/api/public/hooks/rescan'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/api/mcp'
    | '/app/agent'
    | '/app/dashboard'
    | '/app/harvest'
    | '/app/honeypots'
    | '/app/mcp'
    | '/app/onboard'
    | '/app/threats'
    | '/trap/$slug'
    | '/api/public/beacon'
    | '/app/campaigns/$id'
    | '/app/campaigns/'
    | '/api/public/hooks/rescan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiMcpRoute: typeof ApiMcpRoute
  TrapSlugRoute: typeof TrapSlugRoute
  ApiPublicBeaconRoute: typeof ApiPublicBeaconRoute
  ApiPublicHooksRescanRoute: typeof ApiPublicHooksRescanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trap/$slug': {
      id: '/trap/$slug'
      path: '/trap/$slug'
      fullPath: '/trap/$slug'
      preLoaderRoute: typeof TrapSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/threats': {
      id: '/app/threats'
      path: '/threats'
      fullPath: '/app/threats'
      preLoaderRoute: typeof AppThreatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboard': {
      id: '/app/onboard'
      path: '/onboard'
      fullPath: '/app/onboard'
      preLoaderRoute: typeof AppOnboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mcp': {
      id: '/app/mcp'
      path: '/mcp'
      fullPath: '/app/mcp'
      preLoaderRoute: typeof AppMcpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/honeypots': {
      id: '/app/honeypots'
      path: '/honeypots'
      fullPath: '/app/honeypots'
      preLoaderRoute: typeof AppHoneypotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/harvest': {
      id: '/app/harvest'
      path: '/harvest'
      fullPath: '/app/harvest'
      preLoaderRoute: typeof AppHarvestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/campaigns/': {
      id: '/app/campaigns/'
      path: '/campaigns'
      fullPath: '/app/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns/$id': {
      id: '/app/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/app/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/beacon': {
      id: '/api/public/beacon'
      path: '/api/public/beacon'
      fullPath: '/api/public/beacon'
      preLoaderRoute: typeof ApiPublicBeaconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/rescan': {
      id: '/api/public/hooks/rescan'
      path: '/api/public/hooks/rescan'
      fullPath: '/api/public/hooks/rescan'
      preLoaderRoute: typeof ApiPublicHooksRescanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHarvestRoute: typeof AppHarvestRoute
  AppHoneypotsRoute: typeof AppHoneypotsRoute
  AppMcpRoute: typeof AppMcpRoute
  AppOnboardRoute: typeof AppOnboardRoute
  AppThreatsRoute: typeof AppThreatsRoute
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHarvestRoute: AppHarvestRoute,
  AppHoneypotsRoute: AppHoneypotsRoute,
  AppMcpRoute: AppMcpRoute,
  AppOnboardRoute: AppOnboardRoute,
  AppThreatsRoute: AppThreatsRoute,
  AppCampaignsIdRoute: AppCampaignsIdRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiMcpRoute: ApiMcpRoute,
  TrapSlugRoute: TrapSlugRoute,
  ApiPublicBeaconRoute: ApiPublicBeaconRoute,
  ApiPublicHooksRescanRoute: ApiPublicHooksRescanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
