/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrapSlugRouteImport } from './routes/trap.$slug'
import { Route as AppThreatsRouteImport } from './routes/app.threats'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppConnectionRouteImport } from './routes/app.connection'
import { Route as AppAgentRouteImport } from './routes/app.agent'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiPublicBeaconRouteImport } from './routes/api/public/beacon'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrapSlugRoute = TrapSlugRouteImport.update({
  id: '/trap/$slug',
  path: '/trap/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppThreatsRoute = AppThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionRoute = AppConnectionRouteImport.update({
  id: '/connection',
  path: '/connection',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBeaconRoute = ApiPublicBeaconRouteImport.update({
  id: '/api/public/beacon',
  path: '/api/public/beacon',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/api/mcp': typeof ApiMcpRoute
  '/app/agent': typeof AppAgentRoute
  '/app/connection': typeof AppConnectionRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/threats': typeof AppThreatsRoute
  '/trap/$slug': typeof TrapSlugRoute
  '/api/public/beacon': typeof ApiPublicBeaconRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/api/mcp': typeof ApiMcpRoute
  '/app/agent': typeof AppAgentRoute
  '/app/connection': typeof AppConnectionRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/threats': typeof AppThreatsRoute
  '/trap/$slug': typeof TrapSlugRoute
  '/api/public/beacon': typeof ApiPublicBeaconRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/api/mcp': typeof ApiMcpRoute
  '/app/agent': typeof AppAgentRoute
  '/app/connection': typeof AppConnectionRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/threats': typeof AppThreatsRoute
  '/trap/$slug': typeof TrapSlugRoute
  '/api/public/beacon': typeof ApiPublicBeaconRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/api/mcp'
    | '/app/agent'
    | '/app/connection'
    | '/app/dashboard'
    | '/app/threats'
    | '/trap/$slug'
    | '/api/public/beacon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/api/mcp'
    | '/app/agent'
    | '/app/connection'
    | '/app/dashboard'
    | '/app/threats'
    | '/trap/$slug'
    | '/api/public/beacon'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/api/mcp'
    | '/app/agent'
    | '/app/connection'
    | '/app/dashboard'
    | '/app/threats'
    | '/trap/$slug'
    | '/api/public/beacon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiMcpRoute: typeof ApiMcpRoute
  TrapSlugRoute: typeof TrapSlugRoute
  ApiPublicBeaconRoute: typeof ApiPublicBeaconRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trap/$slug': {
      id: '/trap/$slug'
      path: '/trap/$slug'
      fullPath: '/trap/$slug'
      preLoaderRoute: typeof TrapSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/threats': {
      id: '/app/threats'
      path: '/threats'
      fullPath: '/app/threats'
      preLoaderRoute: typeof AppThreatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connection': {
      id: '/app/connection'
      path: '/connection'
      fullPath: '/app/connection'
      preLoaderRoute: typeof AppConnectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/beacon': {
      id: '/api/public/beacon'
      path: '/api/public/beacon'
      fullPath: '/api/public/beacon'
      preLoaderRoute: typeof ApiPublicBeaconRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppConnectionRoute: typeof AppConnectionRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppThreatsRoute: typeof AppThreatsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppConnectionRoute: AppConnectionRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppThreatsRoute: AppThreatsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiMcpRoute: ApiMcpRoute,
  TrapSlugRoute: TrapSlugRoute,
  ApiPublicBeaconRoute: ApiPublicBeaconRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
